import Head from "next/head";
import Components from "@/components"
export default function Home() {
  // const Sections = Components.se
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          hii
        </main>
    </>
  );
}
